import pandas as pd

# Dados do arquivo
dados = """
23E3;ANNA ARIELLY FERNANDES SOUSA;CCECADBEDCEABEBECCDBDCBWADBEEBCBEEDAEDBDDEEECECDCCCCEDCAEDEBBCBBBDBCDCABCCDEABCACEADDCAEBB
23E3;ANNA BEATRIZ AZEVEDO DA SILVA;CCCBDCABAAAABECEADBBDCEBDCABDCAWDCAEECCEBEEABEAECBBCEBDACDBEACBDDACDBAACDDCCACBDDBACDDCBDD
23E3;ANA RAISSA FERNANDES PINHEIRO;CACBBCABDAACEEBAEDCADCBBCADCADBAECBCCDCEBABDBECEDCECEDDCCCCDCDBEBADCBDEZCDCBEABBCDAACDDDDD
23E3;ANA LETICIA BESSA REGO DE ARAUJO;DAEBBCDCDBECBCEAACBEDCACACADCCDAEDEBBABEBBEACDBCCBBDEDABBDDCADBCDCABADECACEEBBACBDACDCDBCD
23E3;BEATRIZ RAMOS LIMA;DDCADAABBBBACEBCBDDAADEECEAEAEDEECABABBCACEBCBBABCDDCACCBCBBDCBCBBEBCBECADBDCCDEACDCEEDBDA
23E3;ARTUR HENRIQUE DOS SANTOS PARENTE;EAEADBABDBDBBBCAEDCAACBCDCDACABDEDACECECCEBEBDBDECEBEDCEDBEDCCBCACDDBDADDBDBECDEADBCBDCCBE
23E3;ANNA CECILIA PINHEIRO CAMPELO;CBCCECABBAABEEDABCCBBCECEBEBEABEECCDECCDEBEEEEBDDDECEACCECAACCCBDABBADCCAABDDCBDBEDCECBCDB
23E3;ARTUR DE MELO MARTINS PINHEIRO;CDCCAEAEDCECEECABADAECEBECDEBCZEEDEBADBEDDEACEDEDCECECDCABCEDCCBAEDBCCADBCEACDABEECCABACDC
23E3;ARTHUR SOUSA VIANA;DBCDCABAABCEDEADCACBACDBADEACDBCEACEBCCAEDECBEBABEEDECBCCBBADCADEAECCBDDCDACCCEDCDADCDCDED
23E3;GABRIQ MARLEY ROCHA DA SILVA;CBCBDCEDDACAAEDABEDAECEBEAABCCDEEDADAAAABBBACEDEACCEEEDCCDCABDCEAAACCACBCABDCCCDCDCACDCCCE
23E3;DAVI BENONE SANTOS COSTA;BBBDDACABDDCAEDADBDCAEBCDCAAAECBECAEBAEDBEEADCBECADBBECACECAACEDCEACCBBEBDAECCAEBDBADAECCC
23E3;BRUNO FREITAS LIMA;CCCDADDBAACBCBBBBACCBEEAADDBCDDDECACEDACAECAEEAEDEBCEEDACABEBBDBEABDCAADDDCAABBDDDDEBEADCB
23E3;EDMARA NUBIA SILVA BRAGA;CCCBDCABAAAABECEADBBDCEBDCABBCBEDCAEECCEDEEACEAEBBBCEAADADACDAEBBABDEEADDDBBAABDCBDBCDDCDD
23E3;JULIA BRAGA VICTOR FERNANDES;BDCCAEACBCBBDBBABDCBAEECDEABDACBDDCBCADBBBBACECECDECEBCAACCEADCBAEEBABCDCAECACBDDBBCDDDDDB
23E3;ISABELE CRISTINE DE SOUZA VASCONCELOS;CACDEDEBDDEAEBCABBCADDBBCEAACDBADDCCCEBBEDEACCCECCECEDZCABBECBBADAEDACCDDECEBABCEDDABBCCAC
23E3;LIVIA MARIA ALMEIDA BARBOSA;CZCEBEDCDEBCBBEEADDDAAEAACBBEBACBACAEDDDBEDAEDDBBAEECCCBDBEAEECDCABBEACDAEBEEBCBCBCADEACAD
23E3;MARIA EDUARDA BORIZ CRUZ BARBOSA;EEBBDABCDCAADECABCECABDECABEECDBBCAAACEEBBDACACDEEABCECCBDECABDECBBDECABDECABDEAABDEDADDDD
23E3;MARIA ALICE LOPES HIPOLITO;CBEEABEBCCEACBCABCEBABBDDCBBCEBBEDCBEADBEBEACDBDCEDCDEDBBCCDACBEAADCDDBEZCBEEBBCDDCDEDCECC
23E3;PAULA BIANCA PEREIRA DE OLIVEIRA LEAL;CCBDEDCADACAEEDAACCBAECABZBEBEDBDDEECCEBECBACZCCAECECBBDBACDACBEBDDBEACDEDADBBDZECDAACDADC
23E3;OTHON FARIAS CAMPOS;CBCDCABEDACBAEDABCCAACECCDAAADDEEEBAEDAEADEACEAEDEECEADCDABACDDDEABCBBDACDCECABCCEACDDCCAE
23E3;NATANAEL MEDEIROS DE FREITAS;DECCCBABBBBBAECABAADAAEDCCDCAAABCDBBBBABABBCBECBBBEBDCDBCAAAACCBEDCCBACCECCAAAAABCCBAACABA
23E3;MARIA TALITA FONTENELE MAXIMIANO;CDCECCCCAACBEEEABAEADAEDDCAAECAEECBBEADDADDABEBCDCACEADDEBBECECDDDCAECABCBCDCCBCCBBECADECB
23E3;THAIS MOITAS CAVALCANTE;CBEZDCDEBDEDCBAABDCAADEDCBABDCAEECAAADCDCBBAECCDCCEAEBDADBCEDBCCCCCCCCCAAAADDDDDADBBDABDCC
"""

# Dividindo os dados em linhas
linhas = dados.strip().split("\n")

# Dividindo cada linha pelos pontos e vírgulas e criando uma lista de dicionários
dados_formatados = []
for linha in linhas:
    valores = linha.split(";")
    dicionario = {
        "ra": valores[0],
        "aluno": valores[1]
    }
    # Separando as letras e criando colunas correspondentes
    letras = list(valores[2])
    for i, letra in enumerate(letras):
        dicionario[f"{i+1}"] = letra
    dados_formatados.append(dicionario)

# Criando o DataFrame
df = pd.DataFrame(dados_formatados)

# Salvando como Excel
df.to_excel("dados_com_colunas.xlsx", index=False)
